version: "3.8"
services:
  uptime:
    container_name: uptime
    env_file:
      - .env
    ports:
      - ${SERVICE_PORT}:3001
    image: louislam/uptime-kuma:latest
    volumes:
      - uptime-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  uptime-data:
